.TH PDF21PNG 1 "June 2025" "pdf21png 2.1.0" "User Commands"

.SH NAME
pdf21png \- convert PDF documents to PNG images (Objective-C implementation)

.SH SYNOPSIS
.B pdf21png
[\fIOPTIONS\fR] \fIinput.pdf\fR [\fIoutput.png\fR]

.SH DESCRIPTION
.B pdf21png
is the Objective-C counterpart to \fBpdf22png\fR.  It shares the same command-line interface, options and behaviour, but is implemented in Objective-C for maximum performance and compatibility with older macOS versions.
.PP
Unless otherwise noted every example from the pdf22png(1) manual applies unchanged to this binary: simply substitute the executable name.

.SH OPTIONS
See pdf22png(1) for the full list of options which are identical.

.SH SEE ALSO
.BR pdf22png (1)

.SH AUTHOR
Written by Adam Twardoch and contributors.

.SH COPYRIGHT
Copyright (C) 2025 Adam Twardoch.  Licensed under the Apache License 2.0. 