name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, macos-13, macos-14]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Check dependencies
      run: make check-deps

    - name: Cache Swift Package Manager
      uses: actions/cache@v4
      with:
        path: pdf22png/.build
        key: ${{ runner.os }}-spm-${{ hashFiles('pdf22png/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Build all implementations
      run: make all

    - name: Install SwiftLint and SwiftFormat
      run: brew install swiftlint swiftformat || true

    - name: Run SwiftLint
      run: |
        if command -v swiftlint &> /dev/null; then
          swiftlint lint pdf22png/Sources/ --strict
        else
          echo "SwiftLint not available, skipping"
        fi

    - name: Run SwiftFormat
      run: |
        if command -v swiftformat &> /dev/null; then
          swiftformat pdf22png/Sources/ --lint --strict
        else
          echo "SwiftFormat not available, skipping"
        fi

    - name: Run tests
      run: make test

    - name: Verify binaries
      run: |
        ./pdf21png/build/pdf21png --version
        ./pdf22png/.build/apple/Products/Release/pdf22png --version || ./pdf22png/.build/release/pdf22png --version

    - name: Upload pdf21png artifact
      uses: actions/upload-artifact@v4
      with:
        name: pdf21png-${{ matrix.os }}
        path: pdf21png/build/pdf21png
        
    - name: Upload pdf22png artifact
      uses: actions/upload-artifact@v4
      with:
        name: pdf22png-${{ matrix.os }}
        path: |
          pdf22png/.build/apple/Products/Release/pdf22png
          pdf22png/.build/release/pdf22png
