name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: ./build.sh

    - name: Install SwiftLint and SwiftFormat
      run: brew install swiftlint swiftformat

    - name: Run SwiftLint
      run: swiftlint lint pdf22png/Sources/ --strict

    - name: Run SwiftFormat
      run: swiftformat pdf22png/Sources/ --lint --strict

    - name: Run tests
      run: ./test_both.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pdf21png
        path: pdf21png/build/pdf21png
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: pdf22png
        path: pdf22png/.build/release/pdf22png
