name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release_pdf21png:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Get version from tag
      id: version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version $VERSION"

    - name: Build
      run: ./build.sh

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}-pdf21png
        name: pdf21png v${{ steps.version.outputs.VERSION }}
        body: |
          # pdf21png v${{ steps.version.outputs.VERSION }}
          
          High-performance PDF to PNG converter for macOS (Objective-C implementation).
          
          See [CHANGELOG.md](https://github.com/twardoch/pdf22png/blob/main/CHANGELOG.md) for details.
        draft: false
        prerelease: false
        files: |
          pdf21png/build/pdf21png

  release_pdf22png:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get version from tag
      id: version
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version $VERSION"

    - name: Build
      run: ./build.sh

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}-pdf22png
        name: pdf22png v${{ steps.version.outputs.VERSION }}
        body: |
          # pdf22png v${{ steps.version.outputs.VERSION }}
          
          Modern, feature-rich PDF to PNG converter for macOS (Swift implementation).
          
          See [CHANGELOG.md](https://github.com/twardoch/pdf22png/blob/main/CHANGELOG.md) for details.
        draft: false
        prerelease: false
        files: |
          pdf22png/.build/release/pdf22png
