name: Update Homebrew Formulas

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to update (e.g., 2.3.1)'
        required: true

jobs:
  update-tap:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Checkout tap repository
      uses: actions/checkout@v4
      with:
        repository: twardoch/homebrew-pdf22png
        path: homebrew-tap
        token: ${{ secrets.TAP_GITHUB_TOKEN }}
    
    - name: Get version and checksums
      id: version
      run: |
        if [ "${{ github.event_name }}" = "release" ]; then
          VERSION="${{ github.event.release.tag_name }}"
        else
          VERSION="v${{ github.event.inputs.version }}"
        fi
        
        # Remove 'v' prefix for formula version
        FORMULA_VERSION="${VERSION#v}"
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        echo "FORMULA_VERSION=$FORMULA_VERSION" >> $GITHUB_OUTPUT
        
        # Download and calculate checksums
        echo "Downloading release assets..."
        RELEASE_URL="https://github.com/twardoch/pdf22png/releases/download/$VERSION"
        
        # Download tarballs
        curl -L -o "pdf21png.tar.gz" "$RELEASE_URL/pdf21png-$VERSION-macos-universal.tar.gz" || {
          echo "Warning: pdf21png tarball not found"
          echo "PDF21_SHA=PLACEHOLDER" >> $GITHUB_OUTPUT
        }
        
        curl -L -o "pdf22png.tar.gz" "$RELEASE_URL/pdf22png-$VERSION-macos-universal.tar.gz" || {
          echo "Warning: pdf22png tarball not found"
          echo "PDF22_SHA=PLACEHOLDER" >> $GITHUB_OUTPUT
        }
        
        # Calculate SHA256
        if [ -f "pdf21png.tar.gz" ]; then
          PDF21_SHA=$(shasum -a 256 pdf21png.tar.gz | cut -d' ' -f1)
          echo "PDF21_SHA=$PDF21_SHA" >> $GITHUB_OUTPUT
        fi
        
        if [ -f "pdf22png.tar.gz" ]; then
          PDF22_SHA=$(shasum -a 256 pdf22png.tar.gz | cut -d' ' -f1)
          echo "PDF22_SHA=$PDF22_SHA" >> $GITHUB_OUTPUT
        fi
    
    - name: Update pdf21png formula
      if: steps.version.outputs.PDF21_SHA != 'PLACEHOLDER'
      run: |
        cd homebrew-tap
        
        # Update version
        sed -i "s/version \".*\"/version \"${{ steps.version.outputs.FORMULA_VERSION }}\"/" Formula/pdf21png.rb
        
        # Update URL
        sed -i "s|url \".*\"|url \"https://github.com/twardoch/pdf22png/releases/download/${{ steps.version.outputs.VERSION }}/pdf21png-${{ steps.version.outputs.VERSION }}-macos-universal.tar.gz\"|" Formula/pdf21png.rb
        
        # Update SHA256
        sed -i "s/sha256 \".*\"/sha256 \"${{ steps.version.outputs.PDF21_SHA }}\"/" Formula/pdf21png.rb
        
        echo "Updated pdf21png.rb"
    
    - name: Update pdf22png formula
      if: steps.version.outputs.PDF22_SHA != 'PLACEHOLDER'
      run: |
        cd homebrew-tap
        
        # Update version
        sed -i "s/version \".*\"/version \"${{ steps.version.outputs.FORMULA_VERSION }}\"/" Formula/pdf22png.rb
        
        # Update URL
        sed -i "s|url \".*\"|url \"https://github.com/twardoch/pdf22png/releases/download/${{ steps.version.outputs.VERSION }}/pdf22png-${{ steps.version.outputs.VERSION }}-macos-universal.tar.gz\"|" Formula/pdf22png.rb
        
        # Update SHA256
        sed -i "s/sha256 \".*\"/sha256 \"${{ steps.version.outputs.PDF22_SHA }}\"/" Formula/pdf22png.rb
        
        echo "Updated pdf22png.rb"
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.TAP_GITHUB_TOKEN }}
        path: homebrew-tap
        commit-message: "Update formulas for version ${{ steps.version.outputs.VERSION }}"
        title: "Update to version ${{ steps.version.outputs.VERSION }}"
        body: |
          Automated update of Homebrew formulas for pdf22png version ${{ steps.version.outputs.VERSION }}.
          
          ## Changes
          - Updated version to ${{ steps.version.outputs.FORMULA_VERSION }}
          - Updated download URLs
          - Updated SHA256 checksums
          
          ## Checksums
          - pdf21png: `${{ steps.version.outputs.PDF21_SHA }}`
          - pdf22png: `${{ steps.version.outputs.PDF22_SHA }}`
          
          This PR was automatically generated by the [update-homebrew workflow](https://github.com/twardoch/pdf22png/actions/workflows/update-homebrew.yml).
        branch: update-${{ steps.version.outputs.VERSION }}
        delete-branch: true
        
    - name: Auto-merge PR (optional)
      if: success() && steps.version.outputs.PDF21_SHA != 'PLACEHOLDER' && steps.version.outputs.PDF22_SHA != 'PLACEHOLDER'
      run: |
        echo "Pull request created successfully."
        echo "To enable auto-merge, configure branch protection rules and add auto-merge label."